---
- hosts: localhost
  name: This is a Playbook
  connection: local
  vars_files: 
  - vars/vars.yml

  tasks:

  - name: render templates to "render"
    template: src=templates/mysolution.j2 dest=/tmp/ansible-report.txt
