
- name: Install packages on control
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - git

- name: unzip lightbulb master
  unarchive:
    copy: yes
    src: lightbulb.tar.gz
    dest: /home/centos/

- name: change ownership
  file:
    recurse: yes
    owner: centos
    group: centos
    path: /home/centos/lightbulb

- name: Create lab inventory directory
  become: no
  file:
    state: directory
    path: /home/centos/lightbulb/lessons/lab_inventory

- name: Set student fact
  set_fact:
    student: '{{ inventory_hostname | regex_replace("\w*-(\w*)-\w*", "\\1") }}'

- name: Setup student inventory in proper spot
  become: no
  copy:
    src: ./{{ student }}-instances.txt
    dest: /home/centos/lightbulb/lessons/lab_inventory/hosts
  when: "student in inventory_hostname"
