- include: provisioner.yml
  when: provision

- include: bootstrap.yml
  when: bootstrap

- name: Email Hosts file
  run_once: yes
  delegate_to: localhost
  sendgrid:
    username: "{{ sendgrid_user }}"
    password: "{{ sendgrid_pass }}"
    subject: "[Ansible] Important Training Details"
    body: |
          Attached is the Ansible inventory file to be used for training.<br>
          Please check your ability to connect to each of the hosts.<br>
          <br>
          The username is '{{ ssh_user }}' and the password is 'changeme123'.<br>
          If you have any issues connecting, please reply to this email to let me know.

    to_addresses: "{{ item.email }}"
    html_body: yes
    from_address: "{{ instructor_email }}"
    attachments:
      - "{{item.username}}-instances.txt"
  with_items: users
  when: email
