ec2_name_prefix: TRAINING
ec2_security_group: insecure_all
ec2_region: us-east-1
ec2_vpc_id: "{{ ec2_regions[ec2_region].vpc }}"
ec2_vpc_subnet_id: "{{ ec2_regions[ec2_region].subnet_id }}"
ec2_key_name: "{{ ec2_regions[ec2_region].key_name }}"
ec2_exact_count: 1
ec2_wait: yes

ec2_lab_node_types:
  - name: control
    type: rhel7

  - name: node1
    type: rhel7

  - name: node2
    type: rhel7

  - name: node3
    type: rhel7

  - name: haproxy
    type: rhel7


# Lookup tables

ec2_regions:
  us-east-1:
    vpc: vpc-06c9a463
    subnet_id: subnet-a2169ed5
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-61bbf104
      centos7-tower: ami-ebedc8fc
      rhel7: ami-85241def
      rhel7-tower: ami-85241def

  us-west-1:
    vpc: vpc-ce1f9aab
    subnet_id: subnet-25b9157c
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-af4333cf
      centos7-tower: ami-c04a00a0
      rhel7: ami-f88fc498
      rhel7-tower: ami-f88fc498

ec2_instance_types:
  centos7:
    ami_id: "{{ ec2_regions[ec2_region].amis.centos7 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

  centos7-tower:
    ami_id: "{{ ec2_regions[ec2_region].amis['centos7-tower'] }}"
    size: t2.medium
    os_type: linux
    disk_space: 20

  # Look for owner 309956199498 to find official Red Hat AMIs
  rhel7:
    ami_id: "{{ ec2_regions[ec2_region].amis.rhel7 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

  rhel7-tower:
    ami_id: "{{ ec2_regions[ec2_region].amis['rhel7-tower'] }}"
    size: t2.medium
    os_type: linux
    disk_space: 20

ec2_login_names:
  rhel7-tower: ec2-user
  rhel7: ec2-user
  centos7-tower: centos
  centos7: centos


# Backwards compatability
types: "{{ ec2_lab_node_types }}"
aws_key_name: "{{ ec2_key_name }}"
