packages:
  - httpd
  - libselinux-python
apache_service: httpd
apache_docroot: /var/www/html
apache_config: /etc/httpd/conf/httpd.conf
sites_availabe: /etc/httpd/conf/sites-available
sites_enabled: /etc/httpd/conf/sites-enabled
apache_dirs:
- "{{ sites_availabe }}"
- "{{ sites_enabled }}"