---
- hosts: localhost
  connection: local

  tasks:

  - name: test
    command: mkdir {{ item }}
    with_items:
    - a
    - b
    register: output
    ignore_errors: true

  - debug: var=output

  - debug: var=output.results|deeplist("stderr")

  - name: output
    debug: msg="Error from mkdir"
    with_items: "{{ output.results|deeplist('stderr') }}"