- name: Set version specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- name: Install {{ firewall_name }} and libselinux-python
  yum:
    name:
      - libselinux-python
      - "{{ firewall_name }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - common

- name: Disable SELinux
  selinux:
    state: permissive
    policy: targeted
  register: selinux_disable
  when: ansible_os_family == 'RedHat'
  notify:
    - reboot
    - wait for instance
  tags:
    - common

- name: Stop and disable firewall
  service:
    name: "{{ firewall_name }}"
    state: stopped
  tags:
    - common

- meta: flush_handlers
  tags:
    - common
