---
# tasks file for apache

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - libselinux-python

- name: copy index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

- name: start and enable apache service
  service: name=httpd state=started enabled=yes