# aws_key_name:
# name_prefix:
provision: no
email: no
bootstrap: no
instance_types:
  centos7:
    ami_id: ami-61bbf104
    size: t2.micro
    os_type: linux
    disk_space: 10
  centos7-tower:
    ami_id: ami-61bbf104
    size: t2.medium
    os_type: linux
    disk_space: 20
  rhel7:
    ami_id: ami-12663b7a
    size: t2.micro
    os_type: linux
    disk_space: 10
  rhel7-tower:
    ami_id: ami-12663b7a
    size: t2.medium
    os_type: linux
    disk_space: 10

aws_region: us-east-1
vpc_id: vpc-06c9a463
vpc_subnet_id: subnet-a2169ed5
ssh_user: centos
admin_password: changeme123

types:
  - name: control
    type: centos7-tower
  - name: node1
    type: centos7
  - name: node2
    type: centos7
  - name: node3
    type: centos7
  - name: haproxy
    type: centos7
