---
# tasks file for collectd
- name: collectd packages installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: collectd_packages
  notify: restart collectd

- name: configure collectd
  template:
    src: collectd.conf.js
    dest: /etc/collectd.conf
  notify: restart collectd

- name: setup configured paths for collectd
  file:
    state: directory
    path: "{{ item }}"
  with_items: collectd_paths
