---
- hosts: tag_env_training
  gather_facts: yes

- hosts: tag_app_training
  name: performs rolling restart
  gather_facts: no
  serial: 1
  sudo: yes

  pre_tasks:

  - name: disable the server in haproxy
    haproxy: action=disable_server host={{ inventory_hostname }} backend=web_backend
    delegate_to: "{{ groups.tag_role_haproxy.0 }}"

  roles:
  - common
  - lameapp

  # These tasks run after the roles:
  post_tasks:
  - name: Wait for webserver to come up
    wait_for: port=80 state=started timeout=60

  - name: enable the server in haproxy
    haproxy: action=enable_server host={{ inventory_hostname }} backend=web_backend
    delegate_to: "{{ groups.tag_role_haproxy.0 }}"

